// Mocks generated by Mockito 5.2.0 from annotations
// in clean_tdd/test/features/data/models/movie/movie_model_test.dart.
// Do not manually edit this file.

import 'package:clean_tdd/features/data/models/movie/movie_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _Fake$MovieModelCopyWith_0<$Res> extends _i1.Fake
    implements _i2.$MovieModelCopyWith<$Res> {}

/// A class which mocks [MovieModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieModel extends _i1.Mock implements _i2.MovieModel {
  MockMovieModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get backdropPath =>
      (super.noSuchMethod(Invocation.getter(#backdropPath), returnValue: '')
          as String);
  @override
  int get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: 0) as int);
  @override
  String get originalTitle =>
      (super.noSuchMethod(Invocation.getter(#originalTitle), returnValue: '')
          as String);
  @override
  String get overview =>
      (super.noSuchMethod(Invocation.getter(#overview), returnValue: '')
          as String);
  @override
  double get popularity =>
      (super.noSuchMethod(Invocation.getter(#popularity), returnValue: 0.0)
          as double);
  @override
  String get posterPath =>
      (super.noSuchMethod(Invocation.getter(#posterPath), returnValue: '')
          as String);
  @override
  String get releaseDate =>
      (super.noSuchMethod(Invocation.getter(#releaseDate), returnValue: '')
          as String);
  @override
  double get voteAverage =>
      (super.noSuchMethod(Invocation.getter(#voteAverage), returnValue: 0.0)
          as double);
  @override
  int get voteCount =>
      (super.noSuchMethod(Invocation.getter(#voteCount), returnValue: 0)
          as int);
  @override
  _i2.$MovieModelCopyWith<_i2.MovieModel> get copyWith =>
      (super.noSuchMethod(Invocation.getter(#copyWith),
              returnValue: _Fake$MovieModelCopyWith_0<_i2.MovieModel>())
          as _i2.$MovieModelCopyWith<_i2.MovieModel>);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}
